/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SolutionsRouteImport } from './routes/solutions'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SitemapRouteImport } from './routes/sitemap'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CaseStudiesRouteImport } from './routes/case-studies'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as ApplyRouteImport } from './routes/apply'
import { Route as AiResearchRouteImport } from './routes/ai-research'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services/index'
import { Route as ServicesWebDevelopmentRouteImport } from './routes/services/web-development'
import { Route as ServicesSoftwareDevelopmentRouteImport } from './routes/services/software-development'
import { Route as ServicesMobileAppDevelopmentRouteImport } from './routes/services/mobile-app-development'
import { Route as ServicesAiErpSolutionsRouteImport } from './routes/services/ai-erp-solutions'
import { Route as ServicesAiDigitalMarketingRouteImport } from './routes/services/ai-digital-marketing'
import { Route as ServicesAiDevelopmentRouteImport } from './routes/services/ai-development'
import { Route as ServicesAiAutomationRouteImport } from './routes/services/ai-automation'
import { Route as ServicesAiAgentsRouteImport } from './routes/services/ai-agents'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsRoute = SolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapRoute = SitemapRouteImport.update({
  id: '/sitemap',
  path: '/sitemap',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesRoute = CaseStudiesRouteImport.update({
  id: '/case-studies',
  path: '/case-studies',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRoute = ApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const AiResearchRoute = AiResearchRouteImport.update({
  id: '/ai-research',
  path: '/ai-research',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesWebDevelopmentRoute = ServicesWebDevelopmentRouteImport.update({
  id: '/web-development',
  path: '/web-development',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesSoftwareDevelopmentRoute =
  ServicesSoftwareDevelopmentRouteImport.update({
    id: '/software-development',
    path: '/software-development',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesMobileAppDevelopmentRoute =
  ServicesMobileAppDevelopmentRouteImport.update({
    id: '/mobile-app-development',
    path: '/mobile-app-development',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesAiErpSolutionsRoute = ServicesAiErpSolutionsRouteImport.update({
  id: '/ai-erp-solutions',
  path: '/ai-erp-solutions',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesAiDigitalMarketingRoute =
  ServicesAiDigitalMarketingRouteImport.update({
    id: '/ai-digital-marketing',
    path: '/ai-digital-marketing',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesAiDevelopmentRoute = ServicesAiDevelopmentRouteImport.update({
  id: '/ai-development',
  path: '/ai-development',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesAiAutomationRoute = ServicesAiAutomationRouteImport.update({
  id: '/ai-automation',
  path: '/ai-automation',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesAiAgentsRoute = ServicesAiAgentsRouteImport.update({
  id: '/ai-agents',
  path: '/ai-agents',
  getParentRoute: () => ServicesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-research': typeof AiResearchRoute
  '/apply': typeof ApplyRoute
  '/blog': typeof BlogRoute
  '/careers': typeof CareersRoute
  '/case-studies': typeof CaseStudiesRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/faq': typeof FaqRoute
  '/industries': typeof IndustriesRoute
  '/portfolio': typeof PortfolioRoute
  '/privacy': typeof PrivacyRoute
  '/products': typeof ProductsRoute
  '/projects': typeof ProjectsRoute
  '/services': typeof ServicesRouteWithChildren
  '/sitemap': typeof SitemapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/solutions': typeof SolutionsRoute
  '/terms': typeof TermsRoute
  '/services/ai-agents': typeof ServicesAiAgentsRoute
  '/services/ai-automation': typeof ServicesAiAutomationRoute
  '/services/ai-development': typeof ServicesAiDevelopmentRoute
  '/services/ai-digital-marketing': typeof ServicesAiDigitalMarketingRoute
  '/services/ai-erp-solutions': typeof ServicesAiErpSolutionsRoute
  '/services/mobile-app-development': typeof ServicesMobileAppDevelopmentRoute
  '/services/software-development': typeof ServicesSoftwareDevelopmentRoute
  '/services/web-development': typeof ServicesWebDevelopmentRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-research': typeof AiResearchRoute
  '/apply': typeof ApplyRoute
  '/blog': typeof BlogRoute
  '/careers': typeof CareersRoute
  '/case-studies': typeof CaseStudiesRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/faq': typeof FaqRoute
  '/industries': typeof IndustriesRoute
  '/portfolio': typeof PortfolioRoute
  '/privacy': typeof PrivacyRoute
  '/products': typeof ProductsRoute
  '/projects': typeof ProjectsRoute
  '/sitemap': typeof SitemapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/solutions': typeof SolutionsRoute
  '/terms': typeof TermsRoute
  '/services/ai-agents': typeof ServicesAiAgentsRoute
  '/services/ai-automation': typeof ServicesAiAutomationRoute
  '/services/ai-development': typeof ServicesAiDevelopmentRoute
  '/services/ai-digital-marketing': typeof ServicesAiDigitalMarketingRoute
  '/services/ai-erp-solutions': typeof ServicesAiErpSolutionsRoute
  '/services/mobile-app-development': typeof ServicesMobileAppDevelopmentRoute
  '/services/software-development': typeof ServicesSoftwareDevelopmentRoute
  '/services/web-development': typeof ServicesWebDevelopmentRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-research': typeof AiResearchRoute
  '/apply': typeof ApplyRoute
  '/blog': typeof BlogRoute
  '/careers': typeof CareersRoute
  '/case-studies': typeof CaseStudiesRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/faq': typeof FaqRoute
  '/industries': typeof IndustriesRoute
  '/portfolio': typeof PortfolioRoute
  '/privacy': typeof PrivacyRoute
  '/products': typeof ProductsRoute
  '/projects': typeof ProjectsRoute
  '/services': typeof ServicesRouteWithChildren
  '/sitemap': typeof SitemapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/solutions': typeof SolutionsRoute
  '/terms': typeof TermsRoute
  '/services/ai-agents': typeof ServicesAiAgentsRoute
  '/services/ai-automation': typeof ServicesAiAutomationRoute
  '/services/ai-development': typeof ServicesAiDevelopmentRoute
  '/services/ai-digital-marketing': typeof ServicesAiDigitalMarketingRoute
  '/services/ai-erp-solutions': typeof ServicesAiErpSolutionsRoute
  '/services/mobile-app-development': typeof ServicesMobileAppDevelopmentRoute
  '/services/software-development': typeof ServicesSoftwareDevelopmentRoute
  '/services/web-development': typeof ServicesWebDevelopmentRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/ai-research'
    | '/apply'
    | '/blog'
    | '/careers'
    | '/case-studies'
    | '/contact'
    | '/cookies'
    | '/faq'
    | '/industries'
    | '/portfolio'
    | '/privacy'
    | '/products'
    | '/projects'
    | '/services'
    | '/sitemap'
    | '/sitemap.xml'
    | '/solutions'
    | '/terms'
    | '/services/ai-agents'
    | '/services/ai-automation'
    | '/services/ai-development'
    | '/services/ai-digital-marketing'
    | '/services/ai-erp-solutions'
    | '/services/mobile-app-development'
    | '/services/software-development'
    | '/services/web-development'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/ai-research'
    | '/apply'
    | '/blog'
    | '/careers'
    | '/case-studies'
    | '/contact'
    | '/cookies'
    | '/faq'
    | '/industries'
    | '/portfolio'
    | '/privacy'
    | '/products'
    | '/projects'
    | '/sitemap'
    | '/sitemap.xml'
    | '/solutions'
    | '/terms'
    | '/services/ai-agents'
    | '/services/ai-automation'
    | '/services/ai-development'
    | '/services/ai-digital-marketing'
    | '/services/ai-erp-solutions'
    | '/services/mobile-app-development'
    | '/services/software-development'
    | '/services/web-development'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/ai-research'
    | '/apply'
    | '/blog'
    | '/careers'
    | '/case-studies'
    | '/contact'
    | '/cookies'
    | '/faq'
    | '/industries'
    | '/portfolio'
    | '/privacy'
    | '/products'
    | '/projects'
    | '/services'
    | '/sitemap'
    | '/sitemap.xml'
    | '/solutions'
    | '/terms'
    | '/services/ai-agents'
    | '/services/ai-automation'
    | '/services/ai-development'
    | '/services/ai-digital-marketing'
    | '/services/ai-erp-solutions'
    | '/services/mobile-app-development'
    | '/services/software-development'
    | '/services/web-development'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AiResearchRoute: typeof AiResearchRoute
  ApplyRoute: typeof ApplyRoute
  BlogRoute: typeof BlogRoute
  CareersRoute: typeof CareersRoute
  CaseStudiesRoute: typeof CaseStudiesRoute
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  FaqRoute: typeof FaqRoute
  IndustriesRoute: typeof IndustriesRoute
  PortfolioRoute: typeof PortfolioRoute
  PrivacyRoute: typeof PrivacyRoute
  ProductsRoute: typeof ProductsRoute
  ProjectsRoute: typeof ProjectsRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  SitemapRoute: typeof SitemapRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SolutionsRoute: typeof SolutionsRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions': {
      id: '/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap': {
      id: '/sitemap'
      path: '/sitemap'
      fullPath: '/sitemap'
      preLoaderRoute: typeof SitemapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies': {
      id: '/case-studies'
      path: '/case-studies'
      fullPath: '/case-studies'
      preLoaderRoute: typeof CaseStudiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-research': {
      id: '/ai-research'
      path: '/ai-research'
      fullPath: '/ai-research'
      preLoaderRoute: typeof AiResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/web-development': {
      id: '/services/web-development'
      path: '/web-development'
      fullPath: '/services/web-development'
      preLoaderRoute: typeof ServicesWebDevelopmentRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/software-development': {
      id: '/services/software-development'
      path: '/software-development'
      fullPath: '/services/software-development'
      preLoaderRoute: typeof ServicesSoftwareDevelopmentRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/mobile-app-development': {
      id: '/services/mobile-app-development'
      path: '/mobile-app-development'
      fullPath: '/services/mobile-app-development'
      preLoaderRoute: typeof ServicesMobileAppDevelopmentRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/ai-erp-solutions': {
      id: '/services/ai-erp-solutions'
      path: '/ai-erp-solutions'
      fullPath: '/services/ai-erp-solutions'
      preLoaderRoute: typeof ServicesAiErpSolutionsRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/ai-digital-marketing': {
      id: '/services/ai-digital-marketing'
      path: '/ai-digital-marketing'
      fullPath: '/services/ai-digital-marketing'
      preLoaderRoute: typeof ServicesAiDigitalMarketingRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/ai-development': {
      id: '/services/ai-development'
      path: '/ai-development'
      fullPath: '/services/ai-development'
      preLoaderRoute: typeof ServicesAiDevelopmentRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/ai-automation': {
      id: '/services/ai-automation'
      path: '/ai-automation'
      fullPath: '/services/ai-automation'
      preLoaderRoute: typeof ServicesAiAutomationRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/ai-agents': {
      id: '/services/ai-agents'
      path: '/ai-agents'
      fullPath: '/services/ai-agents'
      preLoaderRoute: typeof ServicesAiAgentsRouteImport
      parentRoute: typeof ServicesRoute
    }
  }
}

interface ServicesRouteChildren {
  ServicesAiAgentsRoute: typeof ServicesAiAgentsRoute
  ServicesAiAutomationRoute: typeof ServicesAiAutomationRoute
  ServicesAiDevelopmentRoute: typeof ServicesAiDevelopmentRoute
  ServicesAiDigitalMarketingRoute: typeof ServicesAiDigitalMarketingRoute
  ServicesAiErpSolutionsRoute: typeof ServicesAiErpSolutionsRoute
  ServicesMobileAppDevelopmentRoute: typeof ServicesMobileAppDevelopmentRoute
  ServicesSoftwareDevelopmentRoute: typeof ServicesSoftwareDevelopmentRoute
  ServicesWebDevelopmentRoute: typeof ServicesWebDevelopmentRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesAiAgentsRoute: ServicesAiAgentsRoute,
  ServicesAiAutomationRoute: ServicesAiAutomationRoute,
  ServicesAiDevelopmentRoute: ServicesAiDevelopmentRoute,
  ServicesAiDigitalMarketingRoute: ServicesAiDigitalMarketingRoute,
  ServicesAiErpSolutionsRoute: ServicesAiErpSolutionsRoute,
  ServicesMobileAppDevelopmentRoute: ServicesMobileAppDevelopmentRoute,
  ServicesSoftwareDevelopmentRoute: ServicesSoftwareDevelopmentRoute,
  ServicesWebDevelopmentRoute: ServicesWebDevelopmentRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AiResearchRoute: AiResearchRoute,
  ApplyRoute: ApplyRoute,
  BlogRoute: BlogRoute,
  CareersRoute: CareersRoute,
  CaseStudiesRoute: CaseStudiesRoute,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  FaqRoute: FaqRoute,
  IndustriesRoute: IndustriesRoute,
  PortfolioRoute: PortfolioRoute,
  PrivacyRoute: PrivacyRoute,
  ProductsRoute: ProductsRoute,
  ProjectsRoute: ProjectsRoute,
  ServicesRoute: ServicesRouteWithChildren,
  SitemapRoute: SitemapRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SolutionsRoute: SolutionsRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
